FROM node:16

RUN apt-get update && apt-get install -y \
    libgtk2.0-0 \
    libgtk-3-0 \
    libgbm-dev \
    libnotify-dev \
    libgconf-2-4 \
    libnss3 \
    libxss1 \
    libasound2 \
    libxtst6 \
    xauth \
    xvfb \
    procps \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN npm init -y

RUN npm install cypress --save-dev
COPY cypress cypress/
COPY cypress.config.js ./

CMD ["xvfb-run", "npx", "cypress", "run", "--spec", "cypress/e2e/ui/**/*.js"]